# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: mcsoftserve

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################

  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

  # DOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/djgpp-static-cmake.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-x86.yml'

  # MacOS ARM 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-arm64.yml'

  # MacOS PPC
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-ppc.yml'


  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-cmake.yml'

  # tvOS (AppleTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-cmake.yml'

  ################################ GAME CONSOLES #############################
  # PS2
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ps2-static-cmake.yml'

  # GameCube
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ngc-static-cmake.yml'

  # PSP
  - project: 'libretro-infrastructure/ci-templates'
    file: '/psp-static-cmake.yml'

  # PS Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static-cmake.yml'

  # Wii
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wii-static-cmake.yml'

  # Wii U
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static-cmake.yml'

  # 3DS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ctr-static-cmake.yml'

  # Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static-cmake.yml'

  #################################### MISC ##################################
  # Dingux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-cmake.yml'

  # Web
  - project: 'libretro-infrastructure/ci-templates'
    file: '/emscripten-static-cmake.yml'

  # Orbis
  - project: 'libretro-infrastructure/ci-templates'
    file: '/orbis-static-cmake.yml'


# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:latest
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - sudo apt-get update -qy
    - sudo apt-get install -qy software-properties-common
    - sudo add-apt-repository -y ppa:savoury1/build-tools
    - sudo apt-get update -qy
    - sudo apt-get install -qy cmake
  # This container's existing installation of CMake is way too old

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-cmake-x86_64
    - .core-defs

# MacOS ARM 64-bit
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs

# MacOS PPC
libretro-osx-cmake-ppc:
  extends:
    - .libretro-osx-cmake-ppc
    - .core-defs

# DOS (huh?)
libretro-djgpp-static-cmake-retroarch-master:
  extends:
    - .libretro-djgpp-static-cmake
    - .core-defs

################################### CELLULAR #################################

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list
    - apt-get update -qy
    - apt-get install -qy cmake/bullseye-backports

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list
    - apt-get update -qy
    - apt-get install -qy cmake/bullseye-backports

# iOS
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-cmake-arm64
    - .core-defs
  variables:
    CORE_ARGS: --toolchain ./cmake/toolchain/ios.toolchain.cmake -DPLATFORM=OS64

# tvOS
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-cmake-arm64
    - .core-defs
  variables:
    CORE_ARGS: --toolchain ./cmake/toolchain/ios.toolchain.cmake -DPLATFORM=TVOS

################################ GAME CONSOLES ###############################
# 3DS
libretro-ctr-static-cmake-retroarch-master:
  extends:
    - .libretro-ctr-static-cmake
    - .core-defs

libretro-libnx-static-cmake-retroarch-master:
  extends:
    - .libretro-libnx-static-cmake
    - .core-defs

libretro-ngc-static-cmake-retroarch-master:
  extends:
    - .libretro-ngc-static-cmake
    - .core-defs

libretro-orbis-static-cmake-retroarch-master:
  extends:
    - .libretro-orbis-static-cmake
    - .core-defs

libretro-ps2-static-cmake-retroarch-master:
  extends:
    - .libretro-ps2-static-cmake
    - .core-defs

libretro-psp-static-cmake-retroarch-master:
  extends:
    - .libretro-psp-static-cmake
    - .core-defs

libretro-vita-static-cmake-retroarch-master:
  extends:
    - .libretro-vita-static-cmake
    - .core-defs

libretro-wii-static-cmake-retroarch-master:
  extends:
    - .libretro-vita-static-cmake
    - .core-defs

libretro-wiiu-static-cmake-retroarch-master:
  extends:
    - .libretro-wiiu-static-cmake
    - .core-defs

#################################### MISC ####################################

# Miyoo
libretro-dingux-cmake-mips32:
  extends:
    - .libretro-dingux-cmake-mips32
    - .core-defs

libretro-miyoo-cmake-arm32:
  extends:
    - .libretro-miyoo-cmake-arm32
    - .core-defs

# Web
libretro-emscripten-static-cmake-retroarch-master:
  extends:
    - .libretro-emscripten-static-cmake-retroarch-master
    - .core-defs